# Generated by Django 3.2.12 on 2023-09-15 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='promodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(max_length=30)),
                ('pbrand', models.CharField(max_length=30)),
                ('pprice', models.IntegerField(default=50)),
                ('pstock', models.CharField(max_length=30)),
            ],
        ),
    ]
